### ISSUE TITLE
Cannot access '/*.jpg': No such file or directory

### ISSUE THREAD

**Issue by bloover** [mrrootsec/vitalsource_downloader#1]
It report below error on Ubuntu 22.04.2 LTS for `img2pdf $(ls $folder_name/*.jpg | sort -n) -o "$folder_name.pdf"`

> Error: ls: cannot access '/*.jpg': No such file or directory

I solved it by using temp solution, enter folder then run `img2pdf $(ls *.jpg | sort -n) -o "folder_name.pdf"`

**Comment by mrrootsec** [comment]
i have added $folder_name for reference (in your case it would be different)

**Comment by mrrootsec** [comment]
i have added $folder_name for reference (in your case it would be different)
